name: Close Jira issue
on:
  issues:
    types:
      - closed

jobs:
  close-issue:
    name: Close Jira issue
    runs-on: ubuntu-latest

    steps:
      - name: Login to Jira
        uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}

      - name: Extract Jira issue key from GitHub issue title
        id: extract-key
        run: |
          ISSUE_TITLE="${{ github.event.issue.title }}"
          echo "Issue Title: $ISSUE_TITLE"

          # Jira 키 추출 (P4-4 형식으로 추출)
          JIRA_KEY=$(echo "$ISSUE_TITLE" | grep -oE '[A-Z]+-[0-9]+')

          # Jira 키가 추출되었는지 확인
          if [[ -z "$JIRA_KEY" ]]; then
            echo "Jira key not found in issue title. Exiting."
            exit 1
          fi

          echo "JIRA_KEY=$JIRA_KEY" >> $GITHUB_ENV
          
          echo "Extracted JIRA_KEY: $JIRA_KEY"

      - name: Close Jira issue
        if: env.JIRA_KEY != ''
        uses: atlassian/gajira-transition@v3
        with:
          issue: ${{ env.JIRA_KEY }}
          transition: Done
